server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: "ANT_PATH_MATCHER"
  datasource:
    username: "root"
    url: "jdbc:mysql://127.0.0.1:3306/miniautorizador"
  # Configuração do Hibernate
  jpa:
    hibernate:
      ddl-auto: "update"
      connection:
        url: "jdbc:mysql://127.0.0.1:3306/miniautorizador"
  # Configuração da JPA
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"



